/**
 * Static site generator: regenerate the original Webflow-designed public site
 * (works.html + projects/<slug>.html) from the CMS (Supabase), keeping the
 * exact Webflow markup, CSS and scripts intact.
 *
 * How it works:
 *   - works.html: the original file is used as-is; only the list of project
 *     cards inside `.work-list.w-dyn-items` is replaced with cards generated
 *     from the currently published CMS projects.
 *   - projects/<slug>.html: an original project page is used as a template
 *     "shell". Only the dynamic regions are swapped (title, description,
 *     category, date, live-link, and the .rich-text-block body). Everything
 *     else (navbar, footer, styles, scripts) stays byte-for-byte identical.
 *   - Project pages whose slugs no longer exist in the CMS (and that were
 *     previously generated by this script) are removed.
 *
 * Usage:
 *   npm run build:site
 *
 * Safe to re-run. Only published projects are rendered.
 */
import { createClient } from "@supabase/supabase-js";
import { readFile, readdir, writeFile, unlink, copyFile } from "node:fs/promises";
import { access } from "node:fs/promises";
import { join } from "node:path";
import { parse } from "node-html-parser";

const EXPORT_DIR =
  process.env.WEBFLOW_EXPORT_DIR ?? join(process.cwd(), "..", "site");
const PROJECTS_DIR = join(EXPORT_DIR, "projects");
const WORKS_FILE = join(EXPORT_DIR, "works.html");
const INDEX_FILE = join(EXPORT_DIR, "index.html");
const ABOUT_FILE = join(EXPORT_DIR, "about.html");
const CONTACT_FILE = join(EXPORT_DIR, "contact.html");
// Legacy Webflow-hosted resume PDFs. build:site rewrites every occurrence of
// these to the CMS-managed resume URL (settings.resume_url).
const LEGACY_RESUME_URLS = [
  "https://cdn.prod.website-files.com/664eb6bdc72329c8129df03f/67b05bfda3b03ecab894611a_Vivek%20Arya%20OG%20Resume.pdf",
  "https://cdn.prod.website-files.com/664eb6bdc72329c8129df03f/66557a4ab5175fc921f3d474_Vivek%20PD%20Resume%20(1).pdf",
];
// Original Webflow hover-card art (migrated CMS card_image_url is often wrong).
const HOME_LIST_IMAGE_BY_SLUG: Record<string, string> = {
  xtudio:
    "https://cdn.prod.website-files.com/664eb6bec72329c8129df0bb/664f69a02602b22be60dfb78_Frame%20179.png",
  schoolpal:
    "https://cdn.prod.website-files.com/664eb6bec72329c8129df0bb/664f6b1af1a4eb0d91c2db83_Frame%202122.png",
  "doremon-den":
    "https://cdn.prod.website-files.com/664eb6bec72329c8129df0bb/664f6c68d6c0630be400f9e1_Frame%2021.png",
  petbow:
    "https://cdn.prod.website-files.com/664eb6bec72329c8129df0bb/664f6c7744c3f4dc72320a9a_Frame%2053.png",
  "concept-design-system":
    "https://cdn.prod.website-files.com/664eb6bec72329c8129df0bb/666698f63ec706f8acf67e40_Slide%2016_9%20-%201.png",
};

// Short company labels from the original Webflow home list (never use subtitle /
// long description under the project title — that breaks the hover layout).
const HOME_COMPANY_BY_SLUG: Record<string, string> = {
  xtudio: "Xapads Media",
  schoolpal: "Microsoft Design Challenge",
  "doremon-den": "Doremon Den",
  petbow: "Competition Entry",
  "concept-design-system": "Programming Pathshala",
};

// How many featured projects to show on the home page.
const HOME_FEATURED_LIMIT = 5;
// Marker comment written into generated project pages so we can tell which
// files this script owns (and may delete when a project is removed).
const GEN_MARKER = "<!-- cms:generated -->";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (
  !SUPABASE_URL ||
  !SERVICE_KEY ||
  SUPABASE_URL.includes("placeholder") ||
  SERVICE_KEY.includes("placeholder")
) {
  console.error(
    "Missing real Supabase credentials. Set NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in .env.local first.",
  );
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_KEY, {
  auth: { persistSession: false },
});

// ── Types (mirrors the Supabase projects table) ──
type TiptapNode = {
  type: string;
  attrs?: Record<string, unknown>;
  content?: TiptapNode[];
  marks?: { type: string; attrs?: Record<string, unknown> }[];
  text?: string;
};

type Project = {
  id: string;
  title: string;
  slug: string;
  subtitle: string | null;
  company_name: string | null;
  live_link: string | null;
  project_date: string | null;
  card_image_url: string | null;
  gallery: string[] | null;
  body: TiptapNode | null;
  featured: boolean;
  sort_order: number;
  status: string;
  categories: { name: string } | null;
};

// ── One-time backup of an original Webflow file before we ever rewrite it ──
async function backupOnce(file: string) {
  const bak = `${file}.bak`;
  try {
    await access(bak);
    return; // backup already exists
  } catch {
    // no backup yet
  }
  try {
    const content = await readFile(file, "utf8");
    // Only back up genuine originals, not something we already generated.
    if (content.includes(GEN_MARKER)) return;
    await copyFile(file, bak);
    console.log(`  · backed up ${file.split("/").pop()} → *.bak`);
  } catch {
    // file may not exist yet; nothing to back up
  }
}

// ── Resume URL managed by the CMS (settings.resume_url); null = leave links ──
let RESUME_URL: string | null = null;

// Swap every legacy Webflow resume PDF link for the CMS-managed URL. If no
// resume is configured yet, this is a safe no-op (originals are left intact).
function applyResume(html: string): string {
  if (!RESUME_URL) return html;
  let out = html;
  for (const legacy of LEGACY_RESUME_URLS) {
    out = out.split(legacy).join(RESUME_URL);
  }
  return out;
}

// ── HTML escaping ──
function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function escAttr(s: string): string {
  return esc(s);
}

function formatDate(iso: string | null): string {
  if (!iso) return "";
  // Stored as YYYY-MM-DD. Parse the parts directly to avoid UTC/local shifts.
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(iso);
  const d = m
    ? new Date(Number(m[1]), Number(m[2]) - 1, Number(m[3]))
    : new Date(iso);
  if (Number.isNaN(d.getTime())) return "";
  return d.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

// ── Inline (marks) rendering: Tiptap inline nodes → HTML string ──
function renderInline(nodes: TiptapNode[] | undefined): string {
  if (!nodes) return "";
  return nodes
    .map((n) => {
      if (n.type === "hardBreak") return "<br/>";
      if (n.type !== "text") return renderInline(n.content);
      let html = esc(n.text ?? "");
      for (const mark of n.marks ?? []) {
        if (mark.type === "bold") html = `<strong>${html}</strong>`;
        else if (mark.type === "italic") html = `<em>${html}</em>`;
        else if (mark.type === "link") {
          const href = escAttr(String(mark.attrs?.href ?? "#"));
          html = `<a href="${href}">${html}</a>`;
        }
      }
      return html;
    })
    .join("");
}

// ── Block rendering: Tiptap doc → .w-richtext inner HTML ──
function renderBlocks(nodes: TiptapNode[] | undefined): string {
  if (!nodes) return "";
  const out: string[] = [];
  for (const node of nodes) {
    switch (node.type) {
      case "heading": {
        const level = Math.min(Math.max(Number(node.attrs?.level ?? 2), 1), 6);
        out.push(`<h${level}>${renderInline(node.content)}</h${level}>`);
        break;
      }
      case "paragraph": {
        const inner = renderInline(node.content);
        // Preserve Webflow's empty-paragraph spacer (zero-width joiner).
        out.push(`<p>${inner || "\u200d"}</p>`);
        break;
      }
      case "bulletList":
      case "orderedList": {
        const tag = node.type === "bulletList" ? "ul" : "ol";
        const items = (node.content ?? [])
          .map((li) => `<li>${renderInline(li.content?.[0]?.content)}</li>`)
          .join("");
        out.push(`<${tag} role="list">${items}</${tag}>`);
        break;
      }
      case "blockquote": {
        const inner = renderBlocks(node.content);
        out.push(`<blockquote>${inner}</blockquote>`);
        break;
      }
      case "horizontalRule": {
        out.push("<hr/>");
        break;
      }
      case "image": {
        const src = escAttr(String(node.attrs?.src ?? ""));
        const alt = escAttr(String(node.attrs?.alt ?? ""));
        const title = node.attrs?.title ? String(node.attrs.title) : "";
        const caption = title
          ? `<figcaption>${esc(title)}</figcaption>`
          : "";
        out.push(
          `<figure class="w-richtext-align-fullwidth w-richtext-figure-type-image"><div><img alt="${alt}" loading="lazy" src="${src}"/></div>${caption}</figure>`,
        );
        break;
      }
      default: {
        if (node.content) out.push(renderBlocks(node.content));
      }
    }
  }
  return out.join("");
}

// ── Build one project card for works.html ──
function buildCard(p: Project): string {
  const cat = p.categories?.name ?? "";
  const img = p.card_image_url ?? "";
  const style =
    "-webkit-transform:translate3d(0, 20vh, 0) scale3d(1, 1, 1) rotateX(-5deg) rotateY(110deg) rotateZ(-5deg) skew(0, 0);-moz-transform:translate3d(0, 20vh, 0) scale3d(1, 1, 1) rotateX(-5deg) rotateY(110deg) rotateZ(-5deg) skew(0, 0);-ms-transform:translate3d(0, 20vh, 0) scale3d(1, 1, 1) rotateX(-5deg) rotateY(110deg) rotateZ(-5deg) skew(0, 0);transform:translate3d(0, 20vh, 0) scale3d(1, 1, 1) rotateX(-5deg) rotateY(110deg) rotateZ(-5deg) skew(0, 0);transform-style:preserve-3d;opacity:0";
  const arrow = `<div class="icon-1x1-tiny w-embed"><svg fill="none" height="420" viewbox="0 0 24 24" width="420" xmlns="http://www.w3.org/2000/svg">
<path d="M13.1722 12L8.22217 7.04999L9.63617 5.63599L16.0002 12L9.63617 18.364L8.22217 16.95L13.1722 12Z" fill="currentColor"></path>
</svg>
</div>`;
  const tag = cat
    ? `<div class="work-card_tag"><div class="text-size-tiny text-style-allcaps text-style-muted">${esc(
        cat,
      )}</div></div>`
    : "";
  return `<div class="work-list-card w-dyn-item" role="listitem"><a class="work-card-item w-inline-block" data-w-id="6338eb0e-f00e-ae9a-5ed8-332a534e54ed" href="/projects/${escAttr(
    p.slug,
  )}" style="${style}"><div class="work-card-image"><div class="work-card-height"></div><img alt="" class="image-fill" loading="lazy" sizes="(max-width: 479px) 74vw, (max-width: 767px) 39vw, (max-width: 991px) 43vw, (max-width: 1919px) 424px, 22vw" src="${escAttr(
    img,
  )}" srcset="${escAttr(
    img,
  )} 1080w"/></div><div class="work-card-text"><div><h3 class="heading-style-h4">${esc(
    p.title,
  )}</h3>${tag}</div><div class="clip"><div class="hover-arrow left">${arrow}</div><div class="hover-arrow">${arrow}</div></div></div></a></div>`;
}

// ── Regenerate works.html (replace the cards inside .work-list) ──
async function buildWorks(projects: Project[]) {
  await backupOnce(WORKS_FILE);
  const html = await readFile(WORKS_FILE, "utf8");
  const root = parse(html, { comment: true });
  const list = root.querySelector(".work-list.w-dyn-items");
  if (!list) {
    console.error("  ✗ Could not find .work-list.w-dyn-items in works.html");
    return;
  }
  const cardsHtml = projects.map(buildCard).join("");
  list.set_content(cardsHtml);
  await writeFile(WORKS_FILE, applyResume(root.toString()), "utf8");
  console.log(`  ✓ works.html — ${projects.length} card(s)`);
}

// ── Build one home-page featured item for index.html ──
function buildHomeItem(p: Project): string {
  // Prefer CMS company_name; fall back to original Webflow short labels.
  // Never fall back to subtitle — those are long descriptions and must stay hidden.
  const company =
    (p.company_name && p.company_name.trim()) ||
    HOME_COMPANY_BY_SLUG[p.slug] ||
    "";
  const cat = p.categories?.name ?? "";
  const img = HOME_LIST_IMAGE_BY_SLUG[p.slug] ?? p.card_image_url ?? "";
  const hoverTransform =
    "-webkit-transform:translate3d(0, 0%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(0, 0%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(0, 0%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(0, 0%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)";
  const lineTransform =
    "-webkit-transform:translate3d(-100%, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(-100%, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(-100%, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(-100%, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)";
  const companyLine = company
    ? `<div class="text-size-tiny text-style-allcaps text-color-white">${esc(
        company,
      )}</div>`
    : "";
  const catText = `<div class="text-size-tiny text-style-allcaps text-color-white">${esc(
    cat,
  )}</div>`;
  // data-w-ids match the original Webflow IX2 targets (hover preview + list item).
  const LIST_ITEM_WID = "1942688e-2c45-8d2b-5bec-1c1493592356";
  const WORK_LINK_WID = "54eb8553-1f76-4eab-2c33-f3a2b2f13857";
  const LIST_IMAGE_WID = "d3eda697-e370-26c6-3aa2-dd1bdc02ade0";
  return `<div class="w-dyn-item" data-w-id="${LIST_ITEM_WID}" role="listitem" thattextsplit="onHover"><a class="work-list-item w-inline-block" data-w-id="${WORK_LINK_WID}" href="/projects/${escAttr(
    p.slug,
  )}"><div class="work-list-grid"><div base="100%" class="work-list-title w-node-_01521a5e-18ee-4a67-e5ed-a483cfb6ffb0-129df094" id="nowThis" thattextsplit="hoverTarget"><h3 class="heading-style-h3 text-color-white">${esc(
    p.title,
  )}</h3>${companyLine}</div><div base="20%" class="clip w-node-a7ada0ce-0806-a150-89a5-c3732ea87a1e-129df094" id="nowThis" thattextsplit="hoverTarget"><div class="hover-text" style="${hoverTransform}">${catText}</div><div class="hover-text bottom-hover-text">${catText}</div></div><div class="list-image" id="w-node-_24cff470-c792-5f36-a823-d03f369a595f-129df094"><div class="list-image-item"><div class="list-image-height" data-w-id="${LIST_IMAGE_WID}" style='background-image:url("${escAttr(
    img,
  )}")'></div></div></div></div><div class="line"><div class="line-fill" style="${lineTransform}"></div></div></a></div>`;
}

// ── Regenerate index.html home page featured list ──
async function buildHome(projects: Project[]) {
  let html: string;
  try {
    await backupOnce(INDEX_FILE);
    html = await readFile(INDEX_FILE, "utf8");
  } catch {
    console.warn("  ! index.html not found — skipping home page.");
    return;
  }
  const root = parse(html, { comment: true });
  const list = root.querySelector(".home-work-cms.w-dyn-items");
  if (!list) {
    console.warn(
      "  ! Could not find .home-work-cms.w-dyn-items in index.html — skipping home page.",
    );
    return;
  }

  // Featured projects first (in priority order); if none are featured, fall
  // back to the top projects by priority so the section is never empty.
  const featured = projects.filter((p) => p.featured);
  const chosen = (featured.length ? featured : projects).slice(
    0,
    HOME_FEATURED_LIMIT,
  );

  list.set_content(chosen.map(buildHomeItem).join(""));
  await writeFile(INDEX_FILE, applyResume(root.toString()), "utf8");
  console.log(`  ✓ index.html — ${chosen.length} featured item(s)`);
}

// ── Find a usable template project page (an original Webflow project file) ──
async function loadTemplateShell(): Promise<string> {
  const files = (await readdir(PROJECTS_DIR)).filter((f) =>
    f.endsWith(".html"),
  );
  // Prefer a known original page; fall back to the first file that is NOT
  // one we generated (so we always template from real Webflow markup).
  const preferred = ["xtudio.html", "schoolpal.html"];
  const candidates = [
    ...preferred.filter((f) => files.includes(f)),
    ...files.filter((f) => !preferred.includes(f)),
  ];
  for (const f of candidates) {
    const c = await readFile(join(PROJECTS_DIR, f), "utf8");
    if (!c.includes(GEN_MARKER)) return c;
  }
  // Everything is generated already — just reuse the first file as a shell.
  return readFile(join(PROJECTS_DIR, candidates[0]), "utf8");
}

// ── Regenerate a single project page from the template shell ──
function buildProjectPage(template: string, p: Project): string {
  const root = parse(template, { comment: true });

  // <html data-item-slug="..."> (de-Webflow renamed from data-wf-item-slug)
  const htmlEl = root.querySelector("html");
  if (htmlEl) htmlEl.setAttribute("data-item-slug", p.slug);

  // Title (hero h1)
  const h1 = root.querySelector(".work-hero_intro .heading-style-h1");
  if (h1) h1.set_content(esc(p.title));

  // Description paragraph
  const desc = root.querySelector(".work-body_descript p");
  if (desc) desc.set_content(esc(p.subtitle ?? ""));

  // Details: [0] category, [1] date
  const details = root.querySelectorAll(
    ".work-body_details .text-style-allcaps",
  );
  if (details[0]) details[0].set_content(esc(p.categories?.name ?? ""));
  if (details[1]) details[1].set_content(esc(formatDate(p.project_date)));

  // Live-project link
  const liveEl = root.querySelector(".work-body_details a.hyperlink");
  if (liveEl) {
    liveEl.setAttribute("href", p.live_link || "#");
    if (!p.live_link) liveEl.setAttribute("style", "display:none");
    else liveEl.removeAttribute("style");
  }

  // Rich text body
  const rich = root.querySelector(".rich-text-block.w-richtext, .w-richtext");
  if (rich) rich.set_content(renderBlocks(p.body?.content));

  // Mark as generated (right after <body>)
  let out = root.toString();
  if (!out.includes(GEN_MARKER)) {
    out = out.replace(/<body>/, `<body>${GEN_MARKER}`);
  }
  return applyResume(out);
}

// ── Rewrite resume links on standalone pages build:site doesn't regenerate ──
async function applyResumeToStandalonePages() {
  if (!RESUME_URL) return; // nothing to do
  for (const file of [ABOUT_FILE, CONTACT_FILE]) {
    let html: string;
    try {
      html = await readFile(file, "utf8");
    } catch {
      continue; // page may not exist
    }
    const swapped = applyResume(html);
    if (swapped === html) continue; // no legacy URLs present
    await backupOnce(file);
    await writeFile(file, swapped, "utf8");
    console.log(`  ✓ ${file.split("/").pop()} — resume link updated`);
  }
}

// Public site contact form → CMS /api/contact
function contactApiUrl(): string {
  const explicit = process.env.CONTACT_API_URL?.trim();
  if (explicit) return explicit.replace(/\/$/, "");
  const site = process.env.NEXT_PUBLIC_SITE_URL?.trim();
  if (site && !site.includes("localhost"))
    return `${site.replace(/\/$/, "")}/api/contact`;
  return "/api/contact";
}

async function applyContactApi() {
  const api = contactApiUrl();

  let html: string;
  try {
    html = await readFile(CONTACT_FILE, "utf8");
  } catch {
    return;
  }

  const next = html.replace(
    /<form([^>]*\bid=["']wf-form-Form["'][^>]*)>/i,
    (_match, attrs: string) => {
      if (/data-contact-api=/.test(attrs)) {
        return `<form${attrs.replace(
          /data-contact-api=["'][^"']*["']/,
          `data-contact-api="${api}"`,
        )}>`;
      }
      return `<form${attrs} data-contact-api="${api}">`;
    },
  );

  if (next === html) {
    if (/data-contact-api=["'][^"']*["']/.test(html)) {
      console.log(`  · contact.html — already → ${api}`);
    } else {
      console.log("  · contact form not found — skipped API wiring");
    }
    return;
  }
  await backupOnce(CONTACT_FILE);
  await writeFile(CONTACT_FILE, next, "utf8");
  console.log(`  ✓ contact.html — form → ${api}`);
}

async function main() {
  console.log("Fetching published projects from CMS…\n");

  // Resume URL is applied to every regenerated page (and about/contact).
  const { data: resumeRow } = await supabase
    .from("settings")
    .select("value")
    .eq("key", "resume_url")
    .maybeSingle();
  RESUME_URL = (resumeRow?.value as string | null) ?? null;
  if (RESUME_URL) console.log(`Resume link → ${RESUME_URL}\n`);

  const { data, error } = await supabase
    .from("projects")
    .select(
      "id, title, slug, subtitle, company_name, live_link, project_date, card_image_url, gallery, body, featured, sort_order, status, categories(name)",
    )
    .eq("status", "published")
    .order("sort_order", { ascending: true })
    .order("project_date", { ascending: false, nullsFirst: false });

  if (error) {
    console.error("Failed to load projects:", error.message);
    process.exit(1);
  }

  const projects = (data ?? []) as unknown as Project[];
  console.log(`Found ${projects.length} published project(s).\n`);

  // 1) Rebuild the works listing.
  await buildWorks(projects);

  // 1b) Rebuild the home page featured list.
  await buildHome(projects);

  // 2) Rebuild each project detail page.
  const template = await loadTemplateShell();
  const liveSlugs = new Set(projects.map((p) => p.slug));

  for (const p of projects) {
    const pageHtml = buildProjectPage(template, p);
    await writeFile(join(PROJECTS_DIR, `${p.slug}.html`), pageHtml, "utf8");
    console.log(`  ✓ projects/${p.slug}.html`);
  }

  // 2b) Rewrite resume links on standalone pages (about/contact).
  await applyResumeToStandalonePages();

  // 2c) Point the contact form at the CMS API.
  await applyContactApi();

  // 3) Remove generated project pages whose project no longer exists.
  const files = (await readdir(PROJECTS_DIR)).filter((f) =>
    f.endsWith(".html"),
  );
  for (const f of files) {
    const slug = f.replace(/\.html$/, "");
    if (liveSlugs.has(slug)) continue;
    const content = await readFile(join(PROJECTS_DIR, f), "utf8");
    if (content.includes(GEN_MARKER)) {
      await unlink(join(PROJECTS_DIR, f));
      console.log(`  – removed projects/${f} (unpublished/deleted)`);
    }
  }

  console.log("\nDone. The public site now reflects the CMS.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
